from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Window(object):
    def setupUi(self, Window):
        Window.setObjectName("Window")
        Window.resize(471, 308)
        font = QtGui.QFont()
        font.setPointSize(8)
        Window.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("1614392314_23-p-temnii-fon-muzika-28.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Window.setWindowIcon(icon)
        Window.setWindowOpacity(0.0)
        Window.setStyleSheet("color: rgb(0, 0, 127);\n"
"background-color: rgb(50, 50, 50);\n"
"\n"
"")
        self.Button_play = QtWidgets.QPushButton(Window)
        self.Button_play.setGeometry(QtCore.QRect(10, 210, 91, 41))
        font = QtGui.QFont()
        font.setPointSize(28)
        self.Button_play.setFont(font)
        self.Button_play.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("icons8-воспроизведение-30.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Button_play.setIcon(icon1)
        self.Button_play.setObjectName("Button_play")
        self.Poloska = QtWidgets.QSlider(Window)
        self.Poloska.setGeometry(QtCore.QRect(10, 180, 451, 22))
        self.Poloska.setOrientation(QtCore.Qt.Horizontal)
        self.Poloska.setObjectName("Poloska")
        self.List_music = QtWidgets.QListView(Window)
        self.List_music.setGeometry(QtCore.QRect(10, 10, 451, 161))
        self.List_music.setObjectName("List_music")
        self.Button_stop = QtWidgets.QPushButton(Window)
        self.Button_stop.setGeometry(QtCore.QRect(100, 210, 91, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.Button_stop.setFont(font)
        self.Button_stop.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("icons8-pause-30.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Button_stop.setIcon(icon2)
        self.Button_stop.setObjectName("Button_stop")
        self.Button_load = QtWidgets.QPushButton(Window)
        self.Button_load.setGeometry(QtCore.QRect(190, 210, 91, 41))
        self.Button_load.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("icons8-загрузки-24.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Button_load.setIcon(icon3)
        self.Button_load.setObjectName("Button_load")
        self.Button_restart = QtWidgets.QPushButton(Window)
        self.Button_restart.setGeometry(QtCore.QRect(280, 210, 91, 41))
        self.Button_restart.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("icons8-повтор-48.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Button_restart.setIcon(icon4)
        self.Button_restart.setObjectName("Button_restart")
        self.Button_random = QtWidgets.QPushButton(Window)
        self.Button_random.setGeometry(QtCore.QRect(370, 210, 91, 41))
        self.Button_random.setText("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("icons8-перемешать-30.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Button_random.setIcon(icon5)
        self.Button_random.setObjectName("Button_random")
        self.Fon = QtWidgets.QLabel(Window)
        self.Fon.setGeometry(QtCore.QRect(-10, -10, 481, 341))
        self.Fon.setAutoFillBackground(False)
        self.Fon.setText("")
        self.Fon.setPixmap(QtGui.QPixmap("maxresdefault.jpg"))
        self.Fon.setScaledContents(True)
        self.Fon.setWordWrap(False)
        self.Fon.setOpenExternalLinks(False)
        self.Fon.setObjectName("Fon")
        self.Fon.raise_()
        self.Button_play.raise_()
        self.Poloska.raise_()
        self.List_music.raise_()
        self.Button_stop.raise_()
        self.Button_load.raise_()
        self.Button_restart.raise_()
        self.Button_random.raise_()

        self.retranslateUi(Window)
        QtCore.QMetaObject.connectSlotsByName(Window)

    def retranslateUi(self, Window):
        _translate = QtCore.QCoreApplication.translate
        Window.setWindowTitle(_translate("Window", "Dialog"))
